### ISSUE TITLE
[Peer-review] Some UI suggestions.

### ISSUE THREAD

**Issue by jkumar10** [airavata-courses/200-ok#54]
Hi Team,

Here are the first few suggestions on the application's front end:

After signing in the UI has lot of blank information. Probably you will work on that in successive projects.
I am able to add parking garage after login which seems to work fine.

After logout the park my car, choose location functionality does not seem to work for me. 
Is this expected or am I doing something wrong?

Thanks

**Comment by maheshbelnekar** [comment]
@jkumar10 Can you tell me what exactly did you notice. 
1. Was the list completely empty? OR 
2. Just that your newly added location was missing?

In any case both of these issues might be because the list was not fetch from the server. It should ideally do, and we are working on that.

Can you please try again, this time refreshing the page?

**Comment by jkumar10** [comment]
Hi,

Yes I saw the list empty after logout.
